# Site settings
title: Everything is Maps
email: contact@philipmallis.com
description: > # this means to ignore newlines until "baseurl:"
  A place for maps by Philip Mallis.
baseurl:  # the subpath of your site, e.g. /blog/
url:  https://everythingismaps.github.io # the base hostname & protocol for your site
twitter_username: philipmallis
github_username:  everythingismaps

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


